Output more-specific error if an integral pointer type is used as a target type for __cheri_addr.
The following now results in a more-specific error:

void f(char * __capability c) {
  char *x = (__cheri_addr char*)c;
}

file.c:5:34: error: integral pointer type 'char *' is not a valid target type for
__cheri_addr: target must be an integer type